name: PyPi Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  checks:
    uses: ./.github/workflows/checks.yaml

  deploy:

    name: PyPi Deploy
    runs-on: ubuntu-latest
    needs: ["checks"]

    env:
      PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install poetry
        run: pip install "poetry<3"

      - name: Skip virtualenv creation
        run: poetry config virtualenvs.create false

      - name: Configure PyPi credentials
        run: poetry config pypi-token.pypi ${{ env.PYPI_TOKEN }}

      - name: Bump Version
        run: poetry version minor

      - name: Git set email
        run: git config --global user.email "github.bot@pypi.org"

      - name: Git set name
        run: git config --global user.name "GitHub Bot"

      - name: Commit
        run: git commit -m "[skip ci] auto-bump-version" -a

      - name: Push
        run: git push

      - name: Deploy to PyPi
        run: poetry --build publish